### ISSUE TITLE
MultiWOZ 2.2

### ISSUE THREAD

**Issue by radi-cho** [bepoetree/MTTOD#11]
Since the official benchmarks for MultiWOZ are computed with their 2.2 version, how can someone reproduce the reported results for MTTOD? What changes were made for 2.2? You said https://github.com/Tomiinek/MultiWOZ_Evaluation has been used - can you share the evaluation script?

**Comment by bepoetree** [comment]
The additional data and descriptions are uploaded to reproduce the MultiWOZ benchmark. Please refer to README file.

**Comment by radi-cho** [comment]
Thank you!
