### ISSUE TITLE
Reader getspan convert_tokens_to_string IndexError: list index out of range when training

### ISSUE THREAD

**Issue by pganesh** [bepoetree/MTTOD#14]
Great work on MTTOD - I'm trying to run the code but unfortunately could not find the exact environments (transformer 4.5 etc.) you have specified

Here's my env

Python 3.10.13
transformers              4.37.2               

When I run the code as follows:

python main.py -version 2.2 -run_type train -model_dir withaux -add_auxiliary_task

I get the following error:

02/20/2024 02:32:56  [INFO] Device: cuda (the number of GPUs: 1)
02/20/2024 02:32:56  [INFO] Set random seed to 42
/opt/conda/envs/mttod/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5.py:240: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be corrected in Transformers v5.
For now, this behavior is kept to avoid breaking backwards compatibility when padding/encoding with `truncation is True`.
- Be aware that you SHOULD NOT rely on t5-base automatically truncating your input to 512 when padding/encoding.
- If you want to encode/pad to sequences longer than 512 you can either instantiate this tokenizer with `model_max_length` or pass `max_length` when encoding/padding.
- To avoid this warning, please instantiate this tokenizer with `model_max_length` set to your preferred value.
  warnings.warn(
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
02/20/2024 02:32:57  [INFO] Encode data and save to data/MultiWOZ_2.2/processed/encoded_data.pkl
train:   0%|                                                                                                                           | 2/8433 [00:00<02:27, 57.21it/s]
Traceback (most recent call last):
  File "/home/ubuntu/mttod/main.py", line 64, in <module>
    main()
  File "/home/ubuntu/mttod/main.py", line 55, in main
    runner = MultiWOZRunner(cfg)
  File "/home/ubuntu/mttod/runner.py", line 297, in __init__
    reader = MultiWOZReader(cfg.backbone, cfg.version)
  File "/home/ubuntu/mttod/reader.py", line 534, in __init__
    super(MultiWOZReader, self).__init__(backbone)
  File "/home/ubuntu/mttod/reader.py", line 420, in __init__
    train = self.encode_data("train")
  File "/home/ubuntu/mttod/reader.py", line 658, in encode_data
    resp_span = self.get_span(
  File "/home/ubuntu/mttod/reader.py", line 838, in get_span
    value = self.tokenizer.convert_tokens_to_string(lex_tokens)
  File "/opt/conda/envs/mttod/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5.py", line 425, in convert_tokens_to_string
    tokens[0] = tokens[0].lstrip(SPIECE_UNDERLINE)
IndexError: list index out of range

**Comment by bepoetree** [comment]
Could you check the lex_tokens (reader.py, line 838) when the error raises?

**Comment by pganesh** [comment]
Thanks for your email
I am printing the following debug values below

                print("Text:", text, file=sys.stderr)
                print("Delex Text:", delex_text, file=sys.stderr)
                print("Tokens:", tokens, file=sys.stderr)
                print("Lex Tokens:", lex_tokens, file=sys.stderr)
                print("Opcode", opcode, file=sys.stderr)

---------------------------------------------------------------------------------------------------------------
It looks lex_tokens is null or empty because the i1, 12 values in opcode
are identical for the records when they error out and the code is doing
lex_tokens = tokens[i1: i2]
---------------------------------------------------------------------------------------------------------------

Not sure where the opcode values are set


Here's what I see for 2.2:

-----------------------------2.2-------------

02/21/2024 01:31:42  [INFO] Encode data and save to
data/MultiWOZ_2.2/processed/encoded_data.pkl

train:   0%|
                                                                    |
0/8431 [00:00<?, ?it/s]

Text: ['<bos_resp>', '▁sure', '▁thing', '▁', '!', '▁', 'i', '▁have',
'▁booked', '▁', 'a', '▁yellow', '▁', 'tes', 'la', '▁for', '▁you', '▁', '.',
'▁', 'if', '▁you', '▁need', '▁it', '▁', ',', '▁the', '▁contact', '▁number',
'▁is', '▁07', '85', '58', '55', '225', '▁', '.', '▁is', '▁there',
'▁anything', '▁else', '▁', 'i', '▁can', '▁help', '▁with', '▁today', '▁',
'?', '<eos_resp>']
Delex Text: ['<bos_resp>', '▁sure', '▁thing', '▁', '!', '▁', 'i', '▁have',
'▁booked', '[value_type]', '▁', 'a', '▁for', '▁you', '▁', '.', '▁', 'if',
'▁you', '▁need', '▁it', '▁', ',', '▁the', '▁contact', '▁number',
'[value_phone]', '▁', '225', '▁', '.', '▁is', '▁there', '▁anything',
'▁else', '▁', 'i', '▁can', '▁help', '▁with', '▁today', '▁', '?',
'<eos_resp>']
Tokens: ['<bos_resp>', '▁sure', '▁thing', '▁', '!', '▁', 'i', '▁have',
'▁booked', '▁', 'a', '▁yellow', '▁', 'tes', 'la', '▁for', '▁you', '▁', '.',
'▁', 'if', '▁you', '▁need', '▁it', '▁', ',', '▁the', '▁contact', '▁number',
'▁is', '▁07', '85', '58', '55', '225', '▁', '.', '▁is', '▁there',
'▁anything', '▁else', '▁', 'i', '▁can', '▁help', '▁with', '▁today', '▁',
'?', '<eos_resp>']
Lex Tokens: []
Opcode ('insert', 9, 9, 9, 10)

train:   0%|
                                                                    |
0/8431 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ubuntu/mttod/main.py", line 64, in <module>
    main()
  File "/home/ubuntu/mttod/main.py", line 55, in main
    runner = MultiWOZRunner(cfg)
  File "/home/ubuntu/mttod/runner.py", line 297, in __init__
    reader = MultiWOZReader(cfg.backbone, cfg.version)
  File "/home/ubuntu/mttod/reader.py", line 534, in __init__
    super(MultiWOZReader, self).__init__(backbone)
  File "/home/ubuntu/mttod/reader.py", line 420, in __init__
    train = self.encode_data("train")
  File "/home/ubuntu/mttod/reader.py", line 658, in encode_data
    resp_span = self.get_span(
  File "/home/ubuntu/mttod/reader.py", line 839, in get_span
    value = self.tokenizer.convert_tokens_to_string(lex_tokens)
  File
"/opt/conda/envs/mttod/lib/python3.10/site-packages/transformers/models/t5/tokenization_t5.py",
line 425, in convert_tokens_to_string
    tokens[0] = tokens[0].lstrip(SPIECE_UNDERLINE)
IndexError: list index out of range
-----------------------------------------------------------------------------

I repeated for the 2.1 version here:

02/21/2024 01:33:25  [INFO] Encode data and save to
data/MultiWOZ_2.1/processed/encoded_data.pkl
train:  26%|██████████████████████████████▌
                                                       | 2170/8434
[00:19<00:58, 106.21it/s]Text: ['<bos_resp>', '▁your', '▁table', '▁has',
'▁been', '▁reserved', '▁', '.', '▁the', '▁reference', '▁#', '▁is', '▁',
'g', '08', '43', 'w', 'f', 'o', '▁', '.', '▁there', '▁are', '▁many',
'▁fun', '▁things', '▁to', '▁do', '▁in', '▁town', '▁', '.', '▁what',
'▁kind', '▁of', '▁things', '▁interest', '▁you', '▁', '?', '▁', '.', '▁',
'.', '▁', '.', '▁museums', '▁', ',', '▁colleges', '▁', '?', '<eos_resp>']
Delex Text: ['<bos_resp>', '▁your', '▁table', '▁has', '▁been', '▁reserved',
'▁', '.', '▁the', '▁reference', '▁#', '▁is', '[value_reference]', '▁', '.',
'▁there', '▁are', '▁[', 'value', '_', 'cho', 'ice', ']', '▁fun', '▁things',
'▁to', '▁do', '▁in', '▁town', '▁', '.', '▁what', '▁kind', '▁of', '▁things',
'▁interest', '▁you', '▁', '?', '▁', '.', '[value_type]', '▁', '.',
'[value_type]', '▁', ',', '▁colleges', '▁', '?', '<eos_resp>']
Tokens: ['<bos_resp>', '▁your', '▁table', '▁has', '▁been', '▁reserved',
'▁', '.', '▁the', '▁reference', '▁#', '▁is', '▁', 'g', '08', '43', 'w',
'f', 'o', '▁', '.', '▁there', '▁are', '▁many', '▁fun', '▁things', '▁to',
'▁do', '▁in', '▁town', '▁', '.', '▁what', '▁kind', '▁of', '▁things',
'▁interest', '▁you', '▁', '?', '▁', '.', '▁', '.', '▁', '.', '▁museums',
'▁', ',', '▁colleges', '▁', '?', '<eos_resp>']
Lex Tokens: []
Opcode ('insert', 42, 42, 41, 42)
train:  26%|██████████████████████████████▋
                                                       | 2174/8434
[00:19<00:57, 109.55it/s]
Traceback (most recent call last):

----------------------------------------------- version 2.0
-----------------------------------------------------------

02/21/2024 01:36:10  [INFO] Encode data and save to
data/MultiWOZ_2.0/processed/encoded_data.pkl
train:   4%|█████▍
                                                         | 379/8434
[00:03<01:16, 105.35it/s]Text: ['<bos_user>', '▁', 'ok', '▁', ',', '▁how',
'▁about', '▁', 's', 'cu', 'dam', 'ores', '▁pun', 'ting', '▁company',
'▁then', '▁', '.', '<eos_user>']
Delex Text: ['<bos_user>', '▁', 'ok', '▁', ',', '▁how', '▁about',
'[value_name]', '▁', 'mp', 'any', '▁then', '▁', '.', '<eos_user>']
Tokens: ['<bos_user>', '▁', 'ok', '▁', ',', '▁how', '▁about', '▁', 's',
'cu', 'dam', 'ores', '▁pun', 'ting', '▁company', '▁then', '▁', '.',
'<eos_user>']
Lex Tokens: []
Opcode ('insert', 7, 7, 7, 8)
train:   5%|█████▍
                                                         | 386/8434
[00:03<01:14, 108.25it/s]
Traceback (most recent call last):

**Comment by pganesh** [comment]
I believe the opcodes are coming from difflib.sequencematcher in Python 3.10.13 - this version of difflib might be behaving differently than the 3.6.x version?

**Comment by bepoetree** [comment]
The error seems to be related to  the version of transformers. It is okay for transformers 4.31.0 (with future warning message)

**Comment by pganesh** [comment]
THanks for the research and suggestion -will try it out

**Comment by pganesh** [comment]
Confirming that going to transformers 4.31.0 fixed the issue

Will close the issue shortly

THanks much for your help!

**Comment by pganesh** [comment]
CLosing issue - please let me know if need help researching why it broke for the later transformer versions
